---
repositories:
  elastic-6.x:
    content: 'deb https://artifacts.elastic.co/packages/oss-6.x/apt stable main'
    key: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'

  kubernetes:
    content: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
    key: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'

  erlang-23.x:
    content: 'deb https://packages.erlang-solutions.com/ubuntu focal contrib'
    key: 'https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc'

  rabbitmq:
    content: 'deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu bionic main'
    key: 'https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey'

  docker-ce:
    content: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
    key: 'https://download.docker.com/linux/ubuntu/gpg'

  elastic-7.x:
    content: 'deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main'
    key: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'

  # postgresql
  pgdg:
    content: 'deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main'
    key: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'

  # postgresql historical packages from apt.postgresql.org
  pgdg-archive:
    content: 'deb http://apt-archive.postgresql.org/pub/repos/apt focal-pgdg-archive main'
    key: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'

  # Provides repmgr
  2ndquadrant-dl-default-release:
    content: 'deb https://dl.2ndquadrant.com/default/release/apt focal-2ndquadrant main'
    key: 'https://dl.2ndquadrant.com/gpg-key.asc'
