---
# Common Redhat family of specific tasks

# Install RedHat extras if on redhat family. This needs to be done first
- name: Restart servers
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
