---
# Documentation: https://repmgr.org/docs/5.2/upgrading-repmgr-extension.html#UPGRADING-MAJOR-VERSION#
# Compatibility: https://repmgr.org/docs/5.2/install-requirements.html#INSTALL-COMPATIBILITY-MATRIX

- name: repmgr for PG {{ upgrade_defaults.pg.version }} | Create upgrade state file
  file:
    path: "{{ upgrade_defaults.repmgr.upgrade.state_file_path }}"
    state: touch
    mode: u=rw,g=r,o=

- name: repmgr for PG {{ upgrade_defaults.pg.version }} | Load postgresql role manifest
  include_vars:
    file: manifest.yml
    name: postgresql_manifest

# repmgr was introduced with epicli v0.6 but the following symlink was added in v0.7 so this task is to ensure it exists
- name: repmgr for PG {{ upgrade_defaults.pg.version }} | Debian | Ensure symlink to config file exists
  file:
    src: "{{ upgrade_defaults.repmgr.config_dir[ansible_os_family] }}/repmgr.conf"
    dest: /etc/repmgr.conf
    state: link
    owner: postgres
    group: postgres
  when: ansible_os_family == 'Debian'

- name: repmgr for PG {{ upgrade_defaults.pg.version }} | Search for primary node
  become_user: postgres
  # command prints primary node name (hostname)
  shell: |-
    set -o pipefail && \
    {{ upgrade_defaults.repmgr.bin_dir[ansible_os_family] }}/repmgr cluster show \
      | awk 'BEGIN{FS="|"} {gsub(/ /,""); if ($3 == "primary") print $2}'
  changed_when: false
  register: find_pg_primary_node
  failed_when: find_pg_primary_node.rc != 0 or find_pg_primary_node.stdout == ""
  run_once: true
  args:
    executable: /bin/bash

# Step: Stop repmgr service
- name: repmgr for PG {{ upgrade_defaults.pg.version }} | Stop repmgr service
  systemd:
    name: "{{ upgrade_defaults.repmgr.service_name[ansible_os_family] }}"
    state: stopped

# Step: Disable repmgr service to prevent packages from prematurely restarting repmgr
- name: repmgr for PG {{ upgrade_defaults.pg.version }} | Disable repmgr service
  systemd:
    name: "{{ upgrade_defaults.repmgr.service_name[ansible_os_family] }}"
    enabled: false

# Step: Install repmgr packages

# On Ubuntu there is dependent 'repmgr-common' package.
# apt module doesn't support --allow-downgrades (see https://github.com/ansible/ansible/issues/29451)
# so we keep installed version if it's newer.
- name: repmgr for PG {{ upgrade_defaults.pg.version }} | Set target version for repmgr-common package
  set_fact:
    repmgr_common_target_version: >-
      {{ _installed_version is version(_target_version, '>') | ternary(_installed_version, _target_version + '-*') }}
  vars:
    _installed_version: "{{ ansible_facts.packages['repmgr-common'][0].version }}"
  when:
    - ansible_os_family == 'Debian'
    - ansible_facts.packages['repmgr-common'] is defined

- name: repmgr for PG {{ upgrade_defaults.pg.version }} | Install repmgr package(s)
  package:
    name: "{{ _packages[ansible_os_family] }}"
    state: present
  vars:
    _packages:
      Debian:
        - "{{ _repmgr_package_name }}={{ _target_version + '-*' }}"
        - repmgr-common={{ repmgr_common_target_version | default(_target_version + '-*') }}
      RedHat:
        - "{{ _repmgr_package_name }}-{{ _target_version }}"
  module_defaults:
    yum: { lock_timeout: "{{ yum_lock_timeout }}" }

- name: repmgr for PG {{ upgrade_defaults.pg.version }} | Update postgres user in sudoers file
  lineinfile:
    path: /etc/sudoers
    regexp: "^postgres ALL=\\(ALL:ALL\\) NOPASSWD:"
    line: >-
      postgres ALL=(ALL:ALL) NOPASSWD:
      /bin/systemctl start {{ upgrade_defaults.pg.service_name[ansible_os_family] }},
      /bin/systemctl stop {{ upgrade_defaults.pg.service_name[ansible_os_family] }},
      /bin/systemctl restart {{ upgrade_defaults.pg.service_name[ansible_os_family] }},
      /bin/systemctl reload {{ upgrade_defaults.pg.service_name[ansible_os_family] }},
      /bin/systemctl start {{ upgrade_defaults.repmgr.service_name[ansible_os_family] }},
      /bin/systemctl stop {{ upgrade_defaults.repmgr.service_name[ansible_os_family] }}
    validate: 'visudo -cf %s'

# Step: Update /etc/default/repmgrd
- name: repmgr for PG {{ upgrade_defaults.pg.version }} | Set 'daemonize=false' option in /etc/default/repmgrd
  lineinfile:
    path: /etc/default/repmgrd
    regexp: ^[#]?REPMGRD_OPTS=
    line: REPMGRD_OPTS="--daemonize=false"
  when: ansible_os_family == 'Debian'

# Step: systemctl daemon-reload
# Step: Restart PostgreSQL
- name: repmgr for PG {{ upgrade_defaults.pg.version }} | Restart PostgreSQL service
  systemd:
    name: "{{ upgrade_defaults.pg.service_name[ansible_os_family] }}"
    state: restarted
    daemon_reload: true

# On Ubuntu the previous task indirectly restarts instantiated service but without waiting for the child service
- name: repmgr for PG {{ upgrade_defaults.pg.version }} | Ensure PostgreSQL instantiated service is running
  systemd:
    name: "{{ upgrade_defaults.pg.instantiated_service_name[ansible_os_family] }}"
    state: started
  when: upgrade_defaults.pg.instantiated_service_name[ansible_os_family] != None

# Step: Update config file
- name: Update repmgr config file
  block:
    - name: repmgr for PG {{ upgrade_defaults.pg.version }} | Get node id
      command: >-
        grep -Po '(?<=^node_id=)\d+' "{{ upgrade_defaults.repmgr.config_dir[ansible_os_family] }}/repmgr.conf"
      register: pg_node_id
      changed_when: false

    - name: repmgr for PG {{ upgrade_defaults.pg.version }} | Replace repmgr config file
      template:
        src: repmgr.conf.j2
        dest: "{{ upgrade_defaults.repmgr.config_dir[ansible_os_family] }}/repmgr.conf"
        owner: postgres
        group: postgres
        mode: u=rw,g=,o=
      vars:
        _node_id: "{{ pg_node_id.stdout }}"
        _pg_bin_dir: "{{ upgrade_defaults.pg.bin_dir[ansible_os_family] }}"
        _pg_data_dir: "{{ upgrade_defaults.pg.data_dir[ansible_os_family] }}"
        _pg_service_name: "{{ upgrade_defaults.pg.service_name[ansible_os_family] }}"
        _replication_user_name: "{{ postgresql_manifest.specification.extensions.replication.replication_user_name }}"
        _repmgr_database: "{{ postgresql_manifest.specification.extensions.replication.repmgr_database }}"
        _repmgr_service_name: "{{ upgrade_defaults.repmgr.service_name[ansible_os_family] }}"

# Step: Execute 'ALTER EXTENSION repmgr UPDATE' (on primary only).
# On standby it fails with error "cannot execute ALTER EXTENSION in a read-only transaction".
- name: repmgr for PG {{ upgrade_defaults.pg.version }} | primary | Update extension
  become_user: postgres
  postgresql_ext:
    name: repmgr
    db: "{{ postgresql_manifest.specification.extensions.replication.repmgr_database }}"
    version: "{{ _split_version[0] }}.{{ _split_version[1] }}"
  vars:
    _split_version: "{{ repmgr.version[ansible_os_family].split('.') }}"
  when: inventory_hostname == find_pg_primary_node.stdout

# Wait for repmgr version propagation to standby
- name: repmgr for PG {{ upgrade_defaults.pg.version }} | standby | Wait for repmgr version sync with primary
  become_user: postgres
  postgresql_query:
    db: "{{ postgresql_manifest.specification.extensions.replication.repmgr_database }}"
    query: SELECT installed_version FROM pg_available_extensions WHERE name = 'repmgr'
  register: query_repmgr_version
  # 'installed_version' keeps only major version (e.g. '5.2')
  until: repmgr.version[ansible_os_family] is match(query_repmgr_version.query_result | json_query('[0].installed_version'))
  retries: 10
  delay: 1
  when: inventory_hostname != find_pg_primary_node.stdout

# Step: Re-enable repmgr service
- name: repmgr for PG {{ upgrade_defaults.pg.version }} | Re-enable repmgr service
  systemd:
    name: "{{ upgrade_defaults.repmgr.service_name[ansible_os_family] }}"
    enabled: true

# Step: Start repmgr service
- name: repmgr for PG {{ upgrade_defaults.pg.version }} | Start repmgr service
  systemd:
    name: "{{ upgrade_defaults.repmgr.service_name[ansible_os_family] }}"
    state: started

- name: repmgr for PG {{ upgrade_defaults.pg.version }} | Remove upgrade state file
  file:
    path: "{{ upgrade_defaults.repmgr.upgrade.state_file_path }}"
    state: absent
