core:  
  azure:  
    resource_group: &resource_group
      name: epi-quick
      location: West Europe
    subscription: YOUR-SUBSCRIPTION-NAME
    ad:
      name: epi-quick
    standard:
      <<: *resource_group
      vms:
        - name: example-vm-ms
          size: Standard_DS2_v2
          count: 1
          roles:
            - linux
            - master
            - worker
            - ca
            - kafka
            - zookeeper
            - prometheus
            - grafana
        - name: example-vm-nd-1
          size: Standard_DS1_v2
          count: 1
          roles:
            - linux
            - worker
            - kafka
            - zookeeper
            - prometheus
            - grafana
        - name: example-vm-nd-2
          size: Standard_DS1_v2
          count: 1
          roles: 
            - linux
            - worker
            - prometheus
            - kafka