---

- name: Create jmx-exporter group
  group:
    name: "{{ specification.jmx_exporter_group }}"
    system: true

- name: Create jmx-exporter user
  user:
    name: "{{ specification.jmx_exporter_user }}"
    group: "{{ specification.jmx_exporter_group }}"
    shell: "/usr/sbin/nologin"
    createhome: false
    system: true

- name: Create JMX Exporter directories
  become: true
  file:
    path: "{{ item }}"
    recurse: true
    owner: root
    group: "{{ specification.jmx_exporter_group }}"
    mode: 0750
    state: directory
  with_items:
    - "{{ specification.jmx_jars_directory }}"

- name: Set JMX Exporter file name to install
  set_fact:
    exporter_file_name: "{{ jmx_exporter_bin_filename }}"

- name: Download JMX Exporter binaries
  include_role:
    name: download
    tasks_from: download_file
  vars:
    file_name: "{{ exporter_file_name }}"

- name: Copy JMX Exporter binaries
  copy:
    src: "{{ download_directory }}/{{ exporter_file_name }}"
    dest: "{{ jmx_exporter_directory }}/{{ exporter_file_name }}"
    owner: "{{ specification.jmx_exporter_user }}"
    group: "{{ specification.jmx_exporter_group }}"
    remote_src: true
    mode: preserve

- name: Prometheus jmx | symlink jar
  become: true
  file:
    src: "{{ jmx_exporter_directory }}/{{ exporter_file_name }}"
    path: "{{ prometheus_jmx_exporter_path }}"
    force: true
    state: link
