---
# Distribution specific packages

prereq-packages:
  # prereq-packages are downloaded without dependencies because of air-gapped mode (dnf localinstall)
  - redhat-logos-httpd  # for httpd

packages:
  from_repo: []
  multiple_versioned: []
  from_url: {}
