---
- name: OpenSearch | Assert input parameters
  assert:
    that:
      - es_api.cert_path is defined
      - es_api.cert_type is defined
      - es_api.cert_type in ['custom', 'demo', 'Epiphany']
      - es_api.key_path  is defined
    quiet: true

- name: OpenSearch | Get info on files
  stat:
    path: "{{ item }}"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: _stat_cert_files
  loop:
    - "{{ es_api.cert_path }}"
    - "{{ es_api.key_path }}"

# Specific case for custom certificates (we don't know the paths so they have to be specified manually)
- name: OpenSearch | Assert files exist
  assert:
    that: stat_result.stat.exists
    fail_msg: "{{ _custom_cert_fail_msg if (es_api.cert_type == 'custom') else _common_fail_msg }}"
    quiet: true
  vars:
    _common_fail_msg: "File not found: '{{ stat_result.item }}'"
    _custom_cert_fail_msg: >-
      {{ _common_fail_msg }}.
      It looks like you use custom certificates.
      Please refer to 'Open Distro for Elasticsearch upgrade' section of How-To docs.
  loop: "{{ _stat_cert_files.results }}"
  loop_control:
    loop_var: stat_result
    label: "{{ stat_result.item }}"  # item = file_path
